### ISSUE TITLE
Deprecated providedService 1.0.0

### ISSUE THREAD

**Issue by noseglid** [idleberg/atom-build-makensis#1]
Next version of Build will no longer support the `^1.0.0` of provided services. This has been deprecated since `v0.50.0` of the build package.

[Please see the documentation to upgrade to version ^2.0.0](https://github.com/noseglid/atom-build/blob/master/create-provider.md).

**Comment by idleberg** [comment]
Thanks, upgraded my provider. However, it seems that jumping to the error has now stopped working entirely (whereas before it only worked when pressing <kbd>F4</kbd> – [remember](https://github.com/noseglid/atom-build/issues/348#issuecomment-198329028)?)

**Comment by noseglid** [comment]
Stopped working since? There hasn't been a release in the last 7 days.

**Comment by idleberg** [comment]
I mean it worked when the provider was still `1.0.0` and stopped since upgrading to `2.0.0`, but maybe that's a coincidence.
